controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

test_route:
    path: /test
    controller: App\Controller\TestController::index

user_create:
    path: /api/users
    controller: 'App\Controller\UserController::createUser'
    methods: [POST]